spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/fom?useUnicode=true&characterEncoding=utf-8
    username: fansofcheer
    password: cheerstyle

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
